### ISSUE TITLE
 Failed to get existing workspaces: AccessDenied: Access Denied

### ISSUE THREAD

**Issue by me009** [secdevops-cuse/CyberRange#42]
Hi,

I got 2 issues when walking through the setup process... at the point of initializing Terraform

1.  From the path below, the '_development_' folder does not exist in the folder structure..

Initialize terraform:
            - execute: 
                - `cd $env.HOMEPATH\Desktop\CyberRange\terraform\environments\development`
                - `terraform.exe init`
        
cd : Cannot find path '...........\CyberRange\terraform\environments\development' because it does not exist.
At line:1 char:1

2. I get this error message when I try to run terraform.exe init

Initializing modules...

Initializing the backend...

**Error: Failed to get existing workspaces: AccessDenied: Access Denied**
        status code: 403, request id: 29DECxxxxxxxxxxxxx, host id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Any tips as to how to resolve this ?

**Comment by cappetta** [comment]
hi @me009  - the development folder was replaced by the region (us-east-1 / eu-west-2) with the goal of keeping things simple.  I found the source of that documentation error and I'm planning to update it later.  I suspect that is the cause of the access denied error.  

to fix it - perform a `cd cd $env.HOMEPATH\Desktop\CyberRange\terraform\environments\eu-west-2` then the `terraform init` step

**Comment by cappetta** [comment]
minor terraform code updates were preformed. 2003 AMI is decom'd ; 2008 AMI required an updated data filter. fixed and pushed
