### ISSUE TITLE
terraform make file

### ISSUE THREAD

**Issue by cappetta** [secdevops-cuse/CyberRange#51]
Create a makefile for the project to help simplify the building / creating of assets.  One thing that I need to determine is if the dependency chain still requires all the specific target components or can instances be booted up with the simple reference to the aws_instance.

**Comment by cappetta** [comment]
Update https://github.com/hashicorp/terraform/issues/21582 when analysis is complete...

**Comment by cappetta** [comment]
makefile exists w/ many commands - dependency chain is fully outlined in the makefile, removed it for the `make kali` command

**Comment by Damanpree** [comment]
Can anyone help me? Coz "make plan" command is not working on my kali linux. Thanks
