### ISSUE TITLE
Document vCPUs required for full range setup

### ISSUE THREAD

**Issue by mstair** [secdevops-cuse/CyberRange#73]
I established a new dedicated account to build out the range. I am hitting ec2 vCPU limits in us-east-1 and need to request increase, looking for guidance on the current required number based on resources. I am trying to calculate based on the terraform instance size configs, but having it documented in the appropriate place may simplify for new users.

**Comment by cappetta** [comment]
@mstair - Thanks for identifying this.  I was unaware of the potential issue with vCPU limits yet I am aware of the instance-type quota increase.  

Here is the service-quota link... https://docs.aws.amazon.com/servicequotas/latest/userguide/request-increase.html#first-concept-chapter

I performed vCPU research.  From what I understand, according to [Amazon's on-demand instance limit guidance](https://aws.amazon.com/ec2/faqs/#EC2_On-Demand_Instance_limits) - there is a [calculator](https://console.aws.amazon.com/ec2/home?region=us-east-1#LimitsCalculator:) that will estimate/calculate the vcpu's needed.  

I currently have a limit of 4,704 vcpu's yet plugging in 30 t2.medium instances suggests I need to increase this by at least 60.  I do not run the range 24x7x365 - perhaps this is why I have not experienced this issue.

![image](https://user-images.githubusercontent.com/5652156/73124345-60b75e00-3f68-11ea-947f-c321ce2df3f2.png)

Looking forward - I'm aiming for 50 assets to be running within the range, this suggests a possible limit of 4,804 vCPUs.  

Adding a documentation label to this so I get it into the wiki / markup docs.  Thanks!

**Comment by shannonmcmurtrey** [comment]
I've been in touch with Amazon about this and it appears that we only need to ask for 60 vCPU's.  The calculation above assumes all instances running across all region's at the same time.

From AWS support...

"Based on the use case in the link you provided, to run 30 t2.medium instances you only need 60 vCPU's and you should only submit a request for 60 vCPU's.

The 4704 vCPU displayed in the link is for all region combined and the 4764 vCPU would be the new combined limit should the 60 vCPU's be approved.

Lets say for example, you intent to run 50 t2.medium instances in Northern Virginia, you would only require 100 vCPU's and the 200 vCPU that has been approved for you account will be more that sufficient."

**Comment by cappetta** [comment]
reviewing open issues/notes.  Thanks @shannonmcmurtrey updating this.   I'd consider this an operations / administrative item solved via documentation given it is a 1-time request to AWS for quota update.  Yet leaving it open to comments in case others think of a better way of handling this

**Comment by cappetta** [comment]
I added a note to this issue in the getting started markup. There is currently a Pull request for a bunch of changes in my personal fork.  I'm working through CICD updates to ensure greater test coverage.  Closing this out 

https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html
