### ISSUE TITLE
Automate machine image builds using Packer

### ISSUE THREAD

**Issue by TheRemover** [secdevops-cuse/CyberRange#76]
I would like to recommend using Packer for building the system images. It would help with maintenance and updates. In addition it could allow for faster deployments in additional AWS regions and potentially other providers.  I would like to assist in this development but would require additional details on the current system builds.

**Comment by cappetta** [comment]
Hi thx for reaching out - apologies for the delayed response, life is busy.  I'm starting to plan the v3 book of work & creating more systems/images is always part of the scope. Packer is currently only a 3rd party use-case, used in the metasploitable projects, when building the entire solution locally. 

if you want to grab a new OVA from vuln hub and prototype the local-to-AMI process flow that would be awesome.  I'm currently uploading OVA's to S3 then performing the image-import task.  

Also not sure if there is an open-source dashboard for tracking packer builds but that would be useful handy here as well.

**Comment by cappetta** [comment]
open to suggestions on packer - especially if you can create a new vulnerable system locally that pushes into an S3 bucket and triggers the AMI import function.  Post a PR if this is possible, would be a nice new feature that could automate maintenance/upkeep of images
