### ISSUE TITLE
Waiting for access..

### ISSUE THREAD

**Issue by wildaces215** [secdevops-cuse/CyberRange#79]
I recently signed up for access to the cyber range and would like to know when I can get access to it....

**Comment by tnantha10** [comment]
Same here.

**Comment by cappetta** [comment]
Saw this a while ago but cleaning up old issues and dealing with some adhoc project mgmt stuff.  

automated access onboarding is being proto-typed, still doing this manually every other week and sending folks emails.  You should definitely be setup by now.  let me know if you are not
